<?xml version="1.0" encoding="utf-8"?><Database Name="TicTacToe" Class="TicTacToeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\ProjectsV14;Initial Catalog=TicTacToe;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Client.Properties.Settings" SettingsPropertyName="TicTacToeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GameHistory" Member="GameHistories">
    <Type Name="GameHistory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Who" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="WithWhom" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="IdResult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GameResult_GameHistory" Member="GameResult" ThisKey="IdResult" OtherKey="Id" Type="GameResult" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameResult" Member="GameResults">
    <Type Name="GameResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="GameResult_GameHistory" Member="GameHistories" ThisKey="Id" OtherKey="IdResult" Type="GameHistory" />
    </Type>
  </Table>
</Database>